// All weapon archetype definitions.
// To add a new weapon: add an entry here, add a powerup card in powerups.js.
export const WEAPON_TYPES = {

  sword: {
    id: 'sword',
    name: 'Sword',
    icon: '⚔️',
    type: 'melee',
    bodyColor: '#aaccff',
    damage: 5,
    attackInterval: 20,
    attackRange: 65,       // auto-fires when enemy center is within 65px
    range: 50,             // hitbox reach in pixels in front of player
    swingDuration: 14,
  },

  magic_missile: {
    id: 'magic_missile',
    name: 'Magic Missile',
    icon: '🔮',
    type: 'magic',
    bodyColor: '#9933cc',
    projectileColor: '#cc66ff',
    trailColor: [180, 80, 255],
    damage: 4,
    attackInterval: 65,
    attackRange: 400,
    projectileSpeed: 6,
    projectileW: 11, projectileH: 9,
    maxRange: 560,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.09,
    maxProjectiles: 1,
    launchStyle:  'arc',
    launchFrames: 18,
  },

  ice_bolt: {
    id: 'ice_bolt',
    name: 'Ice Bolt',
    icon: '❄️',
    type: 'magic',
    bodyColor: '#66ccff',
    projectileColor: '#aaeeff',
    trailColor: [100, 200, 255],
    damage: 3,
    attackInterval: 70,
    attackRange: 400,
    projectileSpeed: 7,
    projectileW: 10, projectileH: 8,
    maxRange: 540,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.08,
    maxProjectiles: 3,
    launchStyle:  'straight',
    launchFrames: 14,
  },

  fire_bolt: {
    id: 'fire_bolt',
    name: 'Fireball',
    icon: '🔥',
    type: 'magic',
    bodyColor: '#ff6600',
    projectileColor: '#ff4400',
    trailColor: [255, 110, 0],
    damage: 7,
    attackInterval: 95,
    attackRange: 350,
    projectileSpeed: 5,
    projectileW: 14, projectileH: 12,
    maxRange: 460,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.06,
    maxProjectiles: 1,
    launchStyle:   'lob',
    launchFrames:  18,
    launchGravity: 0.38,
  },

  lightning_bolt: {
    id: 'lightning_bolt',
    name: 'Lightning',
    icon: '⚡',
    type: 'magic',
    bodyColor: '#ffff44',
    projectileColor: '#ffffff',
    trailColor: [255, 255, 80],
    damage: 2,
    attackInterval: 32,
    attackRange: 330,
    projectileSpeed: 14,
    projectileW: 6, projectileH: 3,
    maxRange: 420,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.15,
    maxProjectiles: 1,
    wobble:     2.5,
    wobbleRate: 0.5,
  },

  chain_lightning: {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    icon: '⚡',          // shown on the travelling projectile
    displayIcon: '🌩️', // shown in HUD, floating icon, pause screen
    type: 'magic',
    bodyColor: '#88ccff',
    projectileColor: '#aaddff',
    trailColor: [120, 200, 255],
    damage: 2,
    attackInterval: 55,
    attackRange: 360,
    projectileSpeed: 6,
    projectileW: 7, projectileH: 4,
    maxRange: 480,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.12,
    maxProjectiles: 1,
    chainCount: 1,
    chainCountByRarity: {
      common: 1, uncommon: 1, rare: 2, epic: 2, legendary: 3, mythic: 3,
    },
    chainRange: 140,
  },

  orb: {
    id: 'orb',
    name: 'Arcane Orb',
    icon: '💠',
    type: 'orb',
    bodyColor: '#44bbff',
    damage: 3,
    attackInterval: 1,
    attackRange: 9999,
    orbitRadius: 55,
    orbitSpeed: 0.025,   // radians per frame
    orbitSize: 8,        // pixel radius of each orb
  },

};
