// All weapon archetype definitions.
// To add a new weapon: add an entry here, add a powerup card in powerups.js.
export const WEAPON_TYPES = {

  sword: {
    id: 'sword',
    name: 'Sword',
    icon: '⚔️',
    type: 'melee',
    bodyColor: '#aaccff',
    damage: 5,
    attackInterval: 20,
    attackRange: 65,       // auto-fires when enemy center is within 65px
    range: 50,             // hitbox reach in pixels in front of player
    swingDuration: 14,
  },

  magic_missile: {
    id: 'magic_missile',
    name: 'Magic Missile',
    icon: '🔮',
    type: 'magic',
    bodyColor: '#9933cc',
    projectileColor: '#cc66ff',
    trailColor: [180, 80, 255],
    damage: 4,
    attackInterval: 65,
    attackRange: 400,
    projectileSpeed: 6,
    projectileW: 11, projectileH: 9,
    maxRange: 800,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.09,
    maxProjectiles: 1,
    launchStyle:   'arc',
    launchFrames:  22,
    launchGravity: 0.28,
    arcVyMult:     0.65,
  },

  ice_bolt: {
    id: 'ice_bolt',
    name: 'Ice Bolt',
    icon: '❄️',
    type: 'magic',
    bodyColor: '#66ccff',
    projectileColor: '#aaeeff',
    trailColor: [100, 200, 255],
    damage: 3,
    attackInterval: 70,
    attackRange: 400,
    projectileSpeed: 7,
    projectileW: 10, projectileH: 8,
    maxRange: 540,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.08,
    maxProjectiles: 3,
    launchStyle:  'straight',
    launchFrames: 14,
  },

  fire_bolt: {
    id: 'fire_bolt',
    name: 'Fireball',
    icon: '🔥',
    type: 'magic',
    bodyColor: '#ff6600',
    projectileColor: '#ff4400',
    trailColor: [255, 110, 0],
    damage: 7,
    attackInterval: 95,
    attackRange: 350,
    projectileSpeed: 5,
    projectileW: 14, projectileH: 12,
    maxRange: 460,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.06,
    maxProjectiles: 1,
    launchStyle:   'lob',
    launchFrames:  18,
    launchGravity: 0.38,
  },

  lightning_bolt: {
    id: 'lightning_bolt',
    name: 'Lightning',
    icon: '⚡',
    type: 'magic',
    bodyColor: '#ffff44',
    projectileColor: '#ffffff',
    trailColor: [255, 255, 80],
    damage: 2,
    attackInterval: 32,
    attackRange: 330,
    projectileSpeed: 14,
    projectileW: 6, projectileH: 3,
    maxRange: 420,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.15,
    maxProjectiles: 1,
    wobble:     2.5,
    wobbleRate: 0.5,
  },

  chain_lightning: {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    icon: '⚡',          // shown on the travelling projectile
    displayIcon: '🌩️', // shown in HUD, floating icon, pause screen
    type: 'magic',
    bodyColor: '#88ccff',
    projectileColor: '#aaddff',
    trailColor: [120, 200, 255],
    damage: 2,
    attackInterval: 55,
    attackRange: 360,
    projectileSpeed: 6,
    projectileW: 7, projectileH: 4,
    maxRange: 480,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.12,
    maxProjectiles: 1,
    chainCount: 1,
    chainCountByRarity: {
      common: 1, uncommon: 1, rare: 2, epic: 2, legendary: 3, mythic: 3,
    },
    chainRange: 140,
  },

  void_bolt: {
    id: 'void_bolt',
    name: 'Void Bolt',
    icon: '🌀',
    displayIcon: '🌀',
    type: 'magic',
    bodyColor: '#220033',
    projectileColor: '#4400aa',
    trailColor: [50, 0, 120],
    damage: 11,
    attackInterval: 130,
    attackRange: 430,
    projectileSpeed: 3.5,
    projectileW: 20, projectileH: 20,
    maxRange: 540,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.03,
    maxProjectiles: 1,
    pierce: true,
    wobble: 1.5, wobbleRate: 0.3,
  },

  arcane_burst: {
    id: 'arcane_burst',
    name: 'Arcane Burst',
    icon: null,
    displayIcon: '💥',
    type: 'magic',
    bodyColor: '#cc44ff',
    projectileColor: '#dd88ff',
    trailColor: [180, 80, 255],
    damage: 3,
    attackInterval: 55,
    attackRange: 270,
    projectileSpeed: 9,
    projectileW: 8, projectileH: 8,
    maxRange: 240,
    spread: 0.5,
    count: 5,
    homing: false,
    homingTurnRate: 0,
    maxProjectiles: 5,
    noIconSpawn: true,
  },

  shadow_bolt: {
    id: 'shadow_bolt',
    name: 'Shadow Bolt',
    icon: null,
    displayIcon: '🌑',
    type: 'magic',
    bodyColor: '#110022',
    projectileColor: '#cc0066',
    trailColor: [160, 0, 80],
    damage: 16,
    attackInterval: 100,
    attackRange: 560,
    projectileSpeed: 18,
    projectileW: 24, projectileH: 8,
    maxRange: 720,
    spread: 0,
    count: 1,
    homing: true,
    homingTurnRate: 0.03,
    maxProjectiles: 1,
  },

  spectral_arrow: {
    id: 'spectral_arrow',
    name: 'Spectral Arrow',
    icon: '🏹',
    type: 'magic',
    bodyColor: '#88ccff',
    projectileColor: '#aaddff',
    trailColor: [140, 200, 255],
    damage: 6,
    attackInterval: 55,
    attackRange: 500,
    projectileSpeed: 9,
    projectileW: 14, projectileH: 4,
    maxRange: 500,
    spread: 0,
    count: 1,
    pierce: true,
    maxProjectiles: 3,
    noIconSpawn: true,
  },

  boulder_toss: {
    id: 'boulder_toss',
    name: 'Boulder Toss',
    icon: '🪨',
    type: 'magic',
    bodyColor: '#886644',
    projectileColor: '#aa8855',
    trailColor: [140, 110, 60],
    damage: 22,
    attackInterval: 160,
    attackRange: 420,
    projectileSpeed: 7,
    projectileW: 22, projectileH: 22,
    maxRange: 700,
    spread: 0,
    count: 1,
    pierce: true,
    homing: false,
    maxProjectiles: 1,
    noIconSpawn: true,
    launchStyle:     'lob',
    launchFrames:    28,
    launchGravity:   0.42,
    persistGravity:  true,
    groundRoll:      true,
  },

  venom_dart: {
    id: 'venom_dart',
    name: 'Poison Bomb',
    icon: '💣',
    displayIcon: '💣',
    type: 'magic',
    bodyColor: '#44aa11',
    projectileColor: '#77dd33',
    trailColor: [60, 190, 30],
    damage: 3,
    attackInterval: 75,
    attackRange: 350,
    projectileSpeed: 6.5,
    projectileW: 14, projectileH: 14,
    maxRange: 480,
    spread: 0,
    count: 1,
    homing: false,
    maxProjectiles: 2,
    noIconSpawn: true,
    launchStyle:    'lob',
    launchFrames:   22,
    launchGravity:  0.32,
    poisonOnDeath:  true,
    poisonRadius:   55,
    poisonDuration: 200,
    poisonDamage:   2,
    poisonTickRate: 22,
  },

  orb: {
    id: 'orb',
    name: 'Arcane Orb',
    icon: '💠',
    type: 'orb',
    bodyColor: '#44bbff',
    damage: 3,
    attackInterval: 1,
    attackRange: 9999,
    orbitRadius: 55,
    orbitSpeed: 0.0375,  // radians per frame
    orbitSize: 8,        // pixel radius of each orb
  },

};
